name: clang-format

on: [push, pull_request]

permissions:
  contents: read

jobs:
  check-clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: npm install
      - name: check clang-format
        run: |
          git config clangFormat.binary node_modules/.bin/clang-format
          git config clangFormat.style file
          npx check-clang-format
